# Generated by Django 2.1 on 2019-07-11 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('identification', models.CharField(blank=True, max_length=64, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=32, null=True)),
                ('birthDate', models.DateField(null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=3, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=16, null=True)),
                ('telp', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', users.models.BaseUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='NA', max_length=2)),
                ('desc', models.CharField(default='NA', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='M', max_length=1)),
                ('desc', models.CharField(default='Male', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='PASSPORT', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='M', max_length=1)),
                ('desc', models.CharField(default='Married', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='APP', max_length=6)),
                ('desc', models.CharField(default='Approved', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VoterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='DPS', max_length=6)),
                ('desc', models.CharField(default='Daftar Pemilih Sementara', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VotingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='T', max_length=1)),
                ('desc', models.CharField(default='TPS', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='VotingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='N', max_length=6)),
                ('desc', models.CharField(default='None', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disability',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.DisabilityType'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Gender'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.IdentificationType'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.MaritalStatus'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
