# Generated by Django 2.1 on 2019-07-11 23:43

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RejectReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.DisabilityType'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.IdentificationType'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.MaritalStatus'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telp',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
