# Generated by Django 2.1 on 2019-07-11 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRegistration',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('votingMethod', models.CharField(choices=[('T', 'TPS'), ('P', 'POS')], default='T', max_length=1)),
                ('registrationType', models.CharField(choices=[('DPS', 'DPS'), ('DPT', 'DPT'), ('DPK', 'DPK'), ('DPTb', 'DPTb'), ('NRSP', 'NO RESPONSE')], default='DPS', max_length=6)),
                ('status', models.CharField(choices=[('APP', 'APPROVED'), ('REJ', 'REJECTED'), ('PEN', 'PENDING'), ('DUP', 'DUPLICATE'), ('MOV', 'MOVED-OUT'), ('DEC', 'DECEASED'), ('UND', 'UNDERAGE'), ('NON', 'NON-CITIZEN')], default='PEN', max_length=6)),
                ('registeredTime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('votingStatus', models.CharField(choices=[('NON', 'NONE'), ('CHKN', 'CHECK IN TPS'), ('SNT', 'BALLOT SENT'), ('RCV', 'BALLOT RECEIVED'), ('RSND', 'RETURNED TO SENDER'), ('VTD', 'VOTED'), ('PLST', 'POSIBLY LOST')], default='NON', max_length=4)),
                ('notes', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
