# Generated by Django 2.1 on 2019-07-11 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190711_1843'),
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personregistration',
            old_name='registeredTime',
            new_name='registered_time',
        ),
        migrations.RemoveField(
            model_name='personregistration',
            name='registrationType',
        ),
        migrations.RemoveField(
            model_name='personregistration',
            name='status',
        ),
        migrations.RemoveField(
            model_name='personregistration',
            name='votingMethod',
        ),
        migrations.RemoveField(
            model_name='personregistration',
            name='votingStatus',
        ),
        migrations.AddField(
            model_name='personregistration',
            name='pending_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PendingReason'),
        ),
        migrations.AddField(
            model_name='personregistration',
            name='registration_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.RegistrationStatus'),
        ),
        migrations.AddField(
            model_name='personregistration',
            name='reject_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.RejectReason'),
        ),
        migrations.AddField(
            model_name='personregistration',
            name='voting_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.VotingMethod'),
        ),
        migrations.AddField(
            model_name='personregistration',
            name='voting_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.VotingStatus'),
        ),
    ]
