# Generated by Django 2.1 on 2019-07-12 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190711_1843'),
        ('voters', '0002_auto_20190711_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='personregistration',
            name='voter_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.VoterType'),
        ),
    ]
